from .utils import ZapNameTable

class ZNT_POOL_OBJDIR(ZapNameTable):
    TABLE = [
        [ 'DMU_POOL_DIRECTORY_OBJECT',     1,                                ],
        [ 'DMU_POOL_CONFIG',               "config",                         ],
        [ 'DMU_POOL_FEATURES_FOR_WRITE',   "features_for_write",             ],
        [ 'DMU_POOL_FEATURES_FOR_READ',    "features_for_read",              ],
        [ 'DMU_POOL_FEATURE_DESCRIPTIONS', "feature_descriptions",           ],
        [ 'DMU_POOL_FEATURE_ENABLED_TXG',  "feature_enabled_txg",            ],
        [ 'DMU_POOL_ROOT_DATASET',         "root_dataset",                   ],
        [ 'DMU_POOL_SYNC_BPOBJ',           "sync_bplist",                    ],
        [ 'DMU_POOL_ERRLOG_SCRUB',         "errlog_scrub",                   ],
        [ 'DMU_POOL_ERRLOG_LAST',          "errlog_last",                    ],
        [ 'DMU_POOL_SPARES',               "spares",                         ],
        [ 'DMU_POOL_DEFLATE',              "deflate",                        ],
        [ 'DMU_POOL_HISTORY',              "history",                        ],
        [ 'DMU_POOL_PROPS',                "pool_props",                     ],
        [ 'DMU_POOL_L2CACHE',              "l2cache",                        ],
        [ 'DMU_POOL_TMP_USERREFS',         "tmp_userrefs",                   ],
        [ 'DMU_POOL_DDT',                  "DDT-%s-%s-%s",                   ],
        [ 'DMU_POOL_DDT_STATS',            "DDT-statistics",                 ],
        [ 'DMU_POOL_CREATION_VERSION',     "creation_version",               ],
        [ 'DMU_POOL_SCAN',                 "scan",                           ],
        [ 'DMU_POOL_FREE_BPOBJ',           "free_bpobj",                     ],
        [ 'DMU_POOL_BPTREE_OBJ',           "bptree_obj",                     ],
        [ 'DMU_POOL_EMPTY_BPOBJ',          "empty_bpobj",                    ],
        [ 'DMU_POOL_CHECKSUM_SALT',        "org.illumos:checksum_salt",      ],
        [ 'DMU_POOL_VDEV_ZAP_MAP',         "com.delphix:vdev_zap_map",       ],
        [ 'DMU_POOL_REMOVING',             "com.delphix:removing",           ],
        [ 'DMU_POOL_OBSOLETE_BPOBJ',       "com.delphix:obsolete_bpobj",     ],
        [ 'DMU_POOL_CONDENSING_INDIRECT',  "com.delphix:condensing_indirect",],
        [ 'DMU_POOL_ZPOOL_CHECKPOINT',     "com.delphix:zpool_checkpoint",   ],
        [ 'DMU_POOL_LOG_SPACEMAP_ZAP',     "com.delphix:log_spacemap_zap",   ],
        [ 'DMU_POOL_DELETED_CLONES',       "com.delphix:deleted_clones",     ],
    ]
